/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdeaIdRouteImport } from './routes/idea.$id'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiPinJsonRouteImport } from './routes/api/pin-json'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaIdRoute = IdeaIdRouteImport.update({
  id: '/idea/$id',
  path: '/idea/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPinJsonRoute = ApiPinJsonRouteImport.update({
  id: '/api/pin-json',
  path: '/api/pin-json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/launch': typeof LaunchRoute
  '/profile': typeof ProfileRoute
  '/api/pin-json': typeof ApiPinJsonRoute
  '/api/upload': typeof ApiUploadRoute
  '/idea/$id': typeof IdeaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/launch': typeof LaunchRoute
  '/profile': typeof ProfileRoute
  '/api/pin-json': typeof ApiPinJsonRoute
  '/api/upload': typeof ApiUploadRoute
  '/idea/$id': typeof IdeaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/launch': typeof LaunchRoute
  '/profile': typeof ProfileRoute
  '/api/pin-json': typeof ApiPinJsonRoute
  '/api/upload': typeof ApiUploadRoute
  '/idea/$id': typeof IdeaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/launch'
    | '/profile'
    | '/api/pin-json'
    | '/api/upload'
    | '/idea/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/launch'
    | '/profile'
    | '/api/pin-json'
    | '/api/upload'
    | '/idea/$id'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/launch'
    | '/profile'
    | '/api/pin-json'
    | '/api/upload'
    | '/idea/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  LaunchRoute: typeof LaunchRoute
  ProfileRoute: typeof ProfileRoute
  ApiPinJsonRoute: typeof ApiPinJsonRoute
  ApiUploadRoute: typeof ApiUploadRoute
  IdeaIdRoute: typeof IdeaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea/$id': {
      id: '/idea/$id'
      path: '/idea/$id'
      fullPath: '/idea/$id'
      preLoaderRoute: typeof IdeaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pin-json': {
      id: '/api/pin-json'
      path: '/api/pin-json'
      fullPath: '/api/pin-json'
      preLoaderRoute: typeof ApiPinJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  LaunchRoute: LaunchRoute,
  ProfileRoute: ProfileRoute,
  ApiPinJsonRoute: ApiPinJsonRoute,
  ApiUploadRoute: ApiUploadRoute,
  IdeaIdRoute: IdeaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
